cabal-version:      3.0
name:               luxury-scheme
version:            0.1.0.0
build-type:         Simple

library
    hs-source-dirs:   src
    exposed-modules:  Env, Eval, Number, Reader, SExpr, Value
    default-language: GHC2024
    build-depends:    base, containers

executable luxury
    main-is:          Main.hs
    hs-source-dirs:   luxury
    default-language: GHC2024
    build-depends:    base, haskeline, luxury-scheme

executable scratch
    main-is:          Main.hs
    hs-source-dirs:   scratch
    default-language: GHC2024
    build-depends:    base, haskeline, luxury-scheme

test-suite luxury-scheme-test
    type:             exitcode-stdio-1.0
    main-is:          Main.hs
    hs-source-dirs:   test
    other-modules:    SExprSpec, ReaderSpec, EvalSpec, ValueSpec
    default-language: GHC2024
    build-depends:    base, hspec, luxury-scheme
